name = "didi-poledance"
compatibility_date = "2025-09-01"
pages_build_output_dir = "./public"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "didi-poledance"
# Replace with the id printed by `npx wrangler d1 create didi-poledance`
database_id = "62b5f4ee-158d-4434-9090-3d8bc480bd16"
